/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 52252684ba0c6acadbcc83ba653752d4)
interface __BaseEnv_Env {
	DB: D1Database;
	UPLOAD_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UPLOAD_TOKEN">> {}
}
